name: Format PHP code with PHP CS Fixer
on:
  # Runs on pushes targeting the default branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Format PHP code with PHP CS Fixer
  format:
    name: Format PHP code with PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, zip, intl, pcntl, bcmath, gd, pdo_mysql, pdo_pgsql, opcache, sockets, exif, imagick, redis, apcu, memcached, mongodb, xdebug
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ansi

      - name: Format PHP code with PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix  --verbose --dry-run --stop-on-violation --using-cache=no
